---
- name: add hosts to Ansible 
  hosts: localhost
  gather_facts: true  
  vars:
      host_ip: "{{ ANSIBLE_HOST_IP }}"
      container_group: "{{ CONTAINER_GROUP }}"
      host_tier: "{{ HOST_TIER }}"
  tasks:
    - name: Check if this node is going to be hosted on the correct tier vm
      fail:
        msg: "TransformCore is an {{ CONTAINER_GROUP }} node, but it's hosted on a machine defined for {{ HOST_TIER }}"
      when: container_group != host_tier
    - name: Add host 
      add_host:
        name: "{{ ANSIBLE_HOST_NAME }}"
        ansible_host: "{{ ANSIBLE_HOST_IP }}"
        ansible_user: "{{ ANSIBLE_USER }}"
      when: 
        - host_ip != "localhost"

- name: docker playbook
  vars:
    host_ip: "{{ ANSIBLE_HOST_IP }}"
  hosts: 
    - "{{ ANSIBLE_HOST_NAME }}"
  gather_facts: false

  tasks:

    - name: docker compose create transform core
      community.docker.docker_compose:
        project_name: alfresco
        definition:
          version: '2'
          services:
            transform:
              image: alfresco/alfresco-transform-core-aio:4.0.0
             
              mem_limit: "{{ MEM_LIMIT }}"
              # environment:
              #   JAVA_OPTS: >-
              #     -XX:MinRAMPercentage="{{ MIN_RAM_PERCENTAGE }}"
              #     -XX:MaxRAMPercentage="{{ MAX_RAM_PERCENTAGE }}"
              ports:
                - "{{ CONTAINER_PORT }}:{{ HOST_PORT }}"
              networks:
                - remote_network

          networks:
            remote_network:
              external: true
              driver: overlay
