---
- name: add hosts to Ansible 
  hosts: localhost
  gather_facts: true  
  vars:
      host_ip: "{{ ANSIBLE_HOST_IP }}"
      container_group: "{{ CONTAINER_GROUP }}"
      host_tier: "{{ HOST_TIER }}"
  tasks:
    - name: Check if this node is going to be hosted on the correct tier vm
      fail:
        msg: "Postgres is an {{ CONTAINER_GROUP }} node, but it's hosted on a machine defined for {{ HOST_TIER }}"
      when: container_group != host_tier
    - name: Add host 
      add_host:
        name: "{{ANSIBLE_HOST_NAME}}"
        ansible_host: "{{ ANSIBLE_HOST_IP }}"
        ansible_user: "{{ ANSIBLE_USER }}"
      when: 
        - host_ip != "localhost"
- hosts: 
    # - target_machine
    - "{{ ANSIBLE_HOST_NAME }}"
  gather_facts: false

  tasks:

    # - name: Make the location
    #   file:
    #     path: /tmp/playing-opera/hello
    #     recurse: true
    #     state: directory

    # - name: Ansible was here
    #   copy:
    #     dest: /tmp/playing-opera/hello/hello.txt
    #     content: "{{ POSTGRES_USER }}"

    - name: postgres docker compose
      community.docker.docker_compose:
        project_name: alfresco_postgres
        definition:
          version: '2'
          services:
            postgres:
              image: postgres:14.4
              mem_limit: 512m
              environment:
                - POSTGRES_PASSWORD=alfresco
                - POSTGRES_USER=alfresco
                - POSTGRES_DB=alfresco
              command: postgres -c max_connections=300 -c log_min_messages=LOG
              ports:
                - "5432:5432"
              networks:
                - remote_network

              volumes:
                - "{{ CLIENT_MNT_DIR }}/{{VOLUME_DIR}}:{{ CONTAINER_DATA_DIR }}"
                # -  /mount/nfs/pgdata-volume:/var/lib/postgresql/data
              # #   -  /mount/nfs/pgdata:/var/lib/postgresql/data
              #   -  /mount/share/pgdata:/var/lib/postgresql/data

                # - type: volume
                #   source: alfresco_postgres_postgres_local # alfresco_postgres_test-volume
                #   target: /var/lib/postgresql/data
                #   volume:
                #     nocopy: true

          networks:
            remote_network:
              external: true
              driver: overlay

          # volumes:
          #   alfresco_postgres_postgres_local:
          #     external: true

            # alfresco_postgres_test-volume:
              # external: true
              # driver_opts:
              #   type: "nfs"
              #   o: "addr=192.168.221.133,nolock,soft,rw" # 129.69.209.200
              #   device: ":/mnt/nfsdir"
# Error response from daemon: error while mounting volume '/var/lib/docker/volumes/jingyue_new-volume/_data': failed to mount local volume: mount :/mnt/nfsdir:/var/lib/docker/volumes/jingyue_new-volume/_data, data: addr=192.168.221.133,nolock,soft: connection timed out
