---
- name: delete
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_file }}"
    ansible_ssh_user: "{{ ssh_user }}"

  tasks:
    - name: Remove Push Gateway instance from Radon Consul
      consul:
        service_name: "{{ pushgateway_ip }}_push_gateway"
        host: "{{ consul_ip }}"
        state: absent
